### ISSUE TITLE
Information about the auth server

### ISSUE THREAD

**Issue by chuckus** [mattmazzola/powerbi-embedded-site#2]
Hi there, thanks for your open source contributions to Power BI Embedded! I much prefer Ember to Angular so am glad I stumbled upon this repo.

I have not developed for Windows environments before and while I can get the app to run locally, but during signin, I run into the issue of not having an auth server running on `localhost:1249` to serve the token. Could you please elaborate how to run this or point in the direction of any documentation? I will be updating the README as I work through this.

**Comment by mattmazzola** [comment]
You would have to register a new application in azure, configure it to need azure management and powerbi permissions, and give it a redirect url of localhost:4200.  Then setup a local server to handle authentication between the Ember app and Azure Active Directory.

For some reason there is a problem with implicit grant flow on the tenant I'm using so I had to cheat a bit with authorization grant flow and this means the server is hardcoded to return a specific redirect instead of re-using the one from the incoming request.

As a temporary solution I have deployed a different instance of the web sever which does reply to localhost:4200 for ember.  I think this will unblock you, if not there isn't another work around besides building your own as I mentioned above.

Change your `authServer` url in the `config/environment.js`:

```
authServer: 'https://powerbiembeddedsite.azurewebsites.net/'
```

**Comment by chazkii** [comment]
Thanks, I had setup a new application in Azure and configured it, but I don't understand what exactly is the local server to handle authentication between the Ember app and Azure Active Directory. Is there a standard server package that I could use? Why cannot the Ember app communicate directly with Azure Active Directory when it comes to authentication, as seen in [here](https://msdn.microsoft.com/en-nz/library/azure/dn645542.aspx)?

**Comment by mattmazzola** [comment]
Is there a standard server package that I could use?
ADAL is the one I used. I think it's this: http://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/

Why cannot the Ember app communicate directly with Azure Active Directory when it comes to authentication?
As I mentioned, the directory has a restriction against using implicit auth flow and I had to use authorization flow and that flow requires use of client secret which cannot be exposed and this usually means having a server.  If you find another way to get implicit flow working let me know.
